### ISSUE TITLE
With 4.2.0 automapper update don't work

### ISSUE THREAD

**Issue by totpero** [danludwig/AutoAutoMapper#7]
Hello,
With last automapper update: https://github.com/AutoMapper/AutoMapper/releases/tag/v4.2.0
this library don't work.
Can you make the update changes?
thanks

**Comment by danludwig** [comment]
@totpero probably not anytime soon. I would however be happy to review and possibly accept a pull request.

**Comment by IanYates** [comment]
I found the same problem.  Then I looked at the AutoAutoMapper source, brought the key class into my own code, and just compiled it into my project.

A method in the new AutoMapper release wasn't backwards compatible from a binary point of view - not sure what the change was.  I just moved on as I had plenty to do :)

However @totpero you may find that's all you need to do.  

@danludwig - perhaps a recompile and retarget to AutoMapper 4.2, plus a push to NuGet, is all that's required?

**Comment by danludwig** [comment]
I agree that a retarget of 4.2 would probably fix this. However @totpero that is a perfectly valid thing that @IanYates did -- just pulling the source code in. It's really just one helper file after all. You shouldn't have to wait on me to continue using the code with AM4.2. 

Again -- if I receive a pull request for this, I would be happy to review it, merge, and push a new nupkg. But atm I don't really use automapper anymore, so I'm not very motivated to do a lot of extra work around it.
